Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -4,23 +4,45 @@ on: [push, workflow_dispatch]
 
 jobs:
   build:
-
     runs-on: windows-latest
 
     steps:
-    - name: Download
-      run: Invoke-WebRequest https://github.com/ngrok/ngroklink-distro/raw/refs/heads/main/ngroklink-windows-amd64.zip -OutFile ngrok.zip
-    - name: Extract
-      run: Expand-Archive ngrok.zip
-    - name: Auth
-      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
+    - name: Download ngrok
+      run: |
+        Invoke-WebRequest https://github.com/ngrok/ngroklink-distro/raw/refs/heads/main/ngroklink-windows-amd64.zip -OutFile ngrok.zip
 
+    - name: Extract ngrok
+      run: |
+        Expand-Archive ngrok.zip -Force
+
+    - name: Locate ngrok
+      id: find_ngrok
+      run: |
+        $ngrok = Get-ChildItem -Recurse -Filter ngrok.exe | Select-Object -First 1
+        
+        if (-not $ngrok) {
+          Write-Error "ngrok.exe not found"
+          exit 1
+        }
+
+        echo "NGROK_PATH=$($ngrok.FullName)" >> $env:GITHUB_ENV
+
+    - name: Authenticate ngrok
       env:
         NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
-    - name: Enable TS
-      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
-    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
-    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
-    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
+      run: |
+        & "$env:NGROK_PATH" authtoken $Env:NGROK_AUTH_TOKEN
+
+    - name: Enable Remote Desktop
+      run: |
+        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
+        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
+        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
+
+    - name: Set Password
+      run: |
+        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
+
     - name: Create Tunnel
-      run: .\ngrok\ngrok.exe tcp 3389
+      run: |
+        & "$env:NGROK_PATH" tcp 3389
